### ISSUE TITLE
Participants.tsv in BIDS: Recommended, Not Required

### ISSUE THREAD

**Issue by Peyman-N** [openMetadataInitiative/bids2openminds#11]
We (myself and @spieschnik) were checking the [bids-example](https://github.com/bids-standard/bids-examples). We encountered an issue while running bids2openminds on the [asl003 dataset](https://github.com/bids-standard/bids-examples/tree/master/asl003). Upon further investigation, it appears that the participants.tsv file is not required. As a temporary solution, I propose modifying the code to skip subject creation if the file is not present. Additionally, in the future, I suggest implementing a backup method based on directory patterns to extract this information.

**Comment by lzehl** [comment]
@Peyman-N can you please run asl003 through a BIDS validation to see/share the output of the validation please?

**Comment by lzehl** [comment]
Modality agnostic files (not all) according to the BIDS specifications (human readable one):

- `dataset_description.json` -> **REQUIRED**
- `README` -> **REQUIRED**
- `CITATION.ccf` -> **RECOMMENDED**
- `CHANGES` -> **RECOMMENDED** (MUST follow [CPAN::Changes::Spec](https://metacpan.org/release/HAARG/CPAN-Changes-0.400002/view//lib/CPAN/Changes/Spec.pod))
- `LICENSE` -> **RECOMMENDED** (MUST be in ASCII or UTF-8 encoding)
- `participants.tsv`, `participants.json` -> **RECOMMENDED**
- `samples.tsv`, `samples.json` -> **REQUIRED** (if `sample-<label>` is present)

**Comment by lzehl** [comment]
We can discuss if we actually push people to a MUST participant.tsc/json when they want to convert to openMINDS.

**Comment by Peyman-N** [comment]
> @Peyman-N can you please run asl003 through a BIDS validation to see/share the output of the validation please?


@lzehl Here is the results of BIDS validator. It seems that validator don't care about `participants` files.


![Screenshot from 2024-04-04 09-09-13](https://github.com/openMetadataInitiative/bids2openminds/assets/56264166/b416720a-92e8-440a-a5c7-119f7454b14d)

**Comment by apdavison** [comment]
> We can discuss if we actually push people to a MUST participant.tsc/json when they want to convert to openMINDS.

I think we should allow conversion to openMINDS for such cases, but we may not accept such datasets in EBRAINS.

**Comment by Peyman-N** [comment]
> We can discuss if we actually push people to a MUST participant.tsc/json when they want to convert to openMINDS.

I think with current structure of openMINDS and its emphasis on subject and subject states, we are implicitly forcing them to do so.

**Comment by lzehl** [comment]
> @lzehl Here is the results of BIDS validator. It seems that validator don't care about `participants` files.

@Peyman-N which fits what I extracted from the human readable BIDS specs. But since validation fails for this example dataset: this also means we should test all example datasets we use to know their behavior in a BIDS validator.
