### ISSUE TITLE
Naming convention for dataset and dataset version 

### ISSUE THREAD

**Issue by Peyman-N** [openMetadataInitiative/bids2openminds#40]
The BIDS datasets have only one filed called `Name`, the instruction for this field is following :

> Name of the dataset.

But in openMINDS we have two fields that can be filled by this information `shortName` and `fullName`. For the moment bids2openminds use this information to fill `shortName` dataset version and `fullName` in dataset. 

@apdavison suggested following :

> Why does the DSV have only "shortName" and the DS only "fullName"? I think it would be better to fill both fields for both the DSV and the DS.

I completely agree with him. @lzehl What are your thoughts on this?

**Comment by lzehl** [comment]
@Peyman-N @apdavison it is important to not mix up EBRAINS practices which openMINDS specs.

If I create DS / DSV outside of EBRAINS I would strongly suggest to always identify all information. Inheritance rules just identify a logic for systems that they can apply if information is not filled out. How this is done is system dependent. I would prefer the EBRAINS KG to actually do a autofill for inherited information  (not leaving it empty and just applying the logic in display)

So: please specify all fields in DS and DSV.
