### ISSUE TITLE
New techniques: inplane T1, inplane T2

### ISSUE THREAD

**Issue by spieschnik** [openMetadataInitiative/bids2openminds#46]
How should inplane T1 and inplane T2 be mapped in openMINDS?
**Suggestions:**
**1.** Mapping to MRIPulseSequence https://openminds.ebrains.eu/instances/MRIPulseSequence/T1 PulseSequence AND technique https://openminds.ebrains.eu/instances/technique/magneticResonanceImaging
Indicating that inplane is a setting/parameter change of the suggested mapping and no new openMINDS instance needs to be created 

**2.** Mapping to technique https://openminds.ebrains.eu/instances/technique/magneticResonanceImaging AND new openMINDS MRIPulseSequence for inplane
Indicating that inplane is a its own MRI pulse sequence or even technique? A new openMINDS instance needs to be created. 
This 2. options makes more sense to me!

**definition:** T1-weighted anatomical image matched to functional acquisition (https://tu-dresden.de/bereichsuebergreifendes/nic/ressourcen/dateien/nic-data-management/series_description_naming_convention_20200618.pdf?lang=en) 

**definition:** T2-weighted anatomical image matched to functional acquisition (https://tu-dresden.de/bereichsuebergreifendes/nic/ressourcen/dateien/nic-data-management/series_description_naming_convention_20200618.pdf?lang=en)

**Comment by yarikoptic** [comment]
FWIW, I recalled about NIDM-Terms for BIDS, but seems tobe quite not useful here: https://nidm-terms.github.io/

![image](https://github.com/openMetadataInitiative/bids2openminds/assets/39889/57caa1b2-cff8-45cc-b0f6-d739553c7ab1)

**Comment by lzehl** [comment]
incorporated in #9
