### ISSUE TITLE
file bundle registration

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/bids2openminds#49]
- sub-01 
  - anat
    - sub-01_anat_file
  - func
    - sub-01_func_file
- sub-02
  - anat
    - sub-02_anat_file
  - func
    - sub-01_func_file

should result in 6 hierarchy-based file bundles :

- file-bundle_sub-01: sub-01_anat_file, sub-01_func_file
- file-bundle_sub-02: sub-02_anat_file, sub-02_func_file 
- file-bundle_sub-01_anat: sub-01_anat_file
- file-bundle_sub-02_anat: sub-02_anat_file
- file-bundle_sub-01_func: sub-01_func_file
- file-bundle_sub-02_func: sub-02_func_file

**Comment by lzehl** [comment]
let's ignore concept-based file bundles for the first version

**Comment by apdavison** [comment]
Should `file-bundle_sub-01` also contain the bundles `file-bundle_sub-01_anat` and `file-bundle_sub-01_func` ?

**Comment by Peyman-N** [comment]
> Should `file-bundle_sub-01` also contain the bundles `file-bundle_sub-01_anat` and `file-bundle_sub-01_func` ?

The relationship is done through reverse linkage. Meaning both `file-bundle_sub-01_anat` and `file-bundle_sub-01_func` have `file-bundle_sub-01` as `isPartOf` property. 
I should mention that the linkage in `File` is reversed too, so the file schema defines it is part of witch file bundles.   

>which file bundles should we have? i.e. should we have a bundle for each directory, or do we collapse directories that only contain another directory (like sub-01 containing ses-01)?

Curent implementation creates a file bundle for each folder.

**Comment by apdavison** [comment]
> The relationship is done through reverse linkage. Meaning both `file-bundle_sub-01_anat` and `file-bundle_sub-01_func` have `file-bundle_sub-01` as `isPartOf` property.
> I should mention that the linkage in `File` is reversed too, so the file schema defines it is part of witch file bundles.

yes, I know. Sorry, my question wasn't clear. I was referring to the way Lyuba expressed the issue description, which leaves it unclear whether `file-bundle_sub-01_anat` and `file-bundle_sub-01_func` _should_ have `file-bundle_sub-01` as `isPartOf` property or not.

**Comment by apdavison** [comment]
> Curent implementation creates a file bundle for each folder.

I saw that, but I also saw a comment from @lzehl on #51 which suggested this should _not_ be the case. My questions were really intended to elicit a clearer definition of the expected behaviour for file bundles, as without this I cannot properly review #51

**Comment by lzehl** [comment]
Let's stick to the following:

Besides registering a flat list of files to the file repo (each file links at least to the file repo), file bundles are created according to the folder structure.

This means for the following example:
```
- sub-01
  - ses-01 
    - anat
      - sub-01_ses-01_anat_file
    - func
      - sub-01_ses-01_func_file
```
2 files

sub-01_ses-01_anat_file 
- isPartOf sub-01_ses-01_anat file bundle
- fileRepository: repo X

sub-01_ses-01_func_file
- isPartOf sub-01_ses-01_func file bundle
- fileRepository: repo X

4 file bundles

sub-01 file bundle
- isPartOf: repo X

sub-01_ses-01 file bundle
- isPartOf sub-01 file bundle

sub-01_ses-01_anat file bundle
- isPartOf sub-01_ses-01 file bundle

sub-01_ses-01_func file bundle
- isPartOf sub-01_ses-01 file bundle

**Comment by Peyman-N** [comment]
`ds000247` had some folder in the meg folder which was ended with .ds. apparently they are not data files but folders, so I adjusted the numbers accordingly. (for example: `ds000247/sub-0002/ses-0001/meg/sub-0002_ses-0001_task-rest_run-01_meg.ds`)
