### ISSUE TITLE
Provide the BIDS directory on the command-line, not through an input prompt

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/bids2openminds#6]
Rather than prompt the user to enter the path to the BIDS directory, they should enter it on the command line, like:
```
$ bids2openminds /path/to/bids/dataset
```

I recommend using [**click**](https://click.palletsprojects.com/) for this (pybids also uses click).

For integration with the pyproject.toml file, see [here](https://click.palletsprojects.com/en/latest/entry-points/).

**Comment by lzehl** [comment]
@apdavison using this via commandline is then an additional option for the initial translation?

**Comment by lzehl** [comment]
I think this should not only be command line option, and it should not be an input() (as it is right now). This should be an attribute of a function. There is going to be more interactive (semi-automatic) elements in the future. I think the bids2openminds has to be a python package with main functions the user can interact with and hidden functions (that do all the translations in the background)

**Comment by lzehl** [comment]
Based on our discussion (@apdavison @Peyman-N) we should go with @apdavison suggestion first and close this ticket. we'll open a separate issue for my concern (later)
