### ISSUE TITLE
creation of duplicate in EBRAINS because of newly assigned @id where not needed.

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/bids2openminds#70]
In EBRAINS test case a new @id was provided for an openMINDS ContentType instead of using the assigned one. Should be checked if this is caused by the code of the converter and correct it if necessary. I can have a look next week.

**Comment by Peyman-N** [comment]
I checked this, the problem was arising from my upload script.
Apparently I was assigning an UUID to `ContentType` then uploading it to kg, which was creating a problem.

**Comment by lzehl** [comment]
Okay. Then this issue is solved.
